export enum ValidateProfileError {
  INVALID_USER_DATA = 'INVALID_USER_DATA',
  INVALID_AGE_DATA = 'INVALID_AGE_DATA',
  INVALID_COUNTRY_DATA = 'INVALID_COUNTRY_DATA',
  NO_DATA = 'NO_DATA',
  SERVER_ERROR = 'SERVER_ERROR'
}
